-- Generated SQL Queries for pulse_university


-- Attendees --
SELECT * FROM Attendee WHERE last_name LIKE 'K%';
UPDATE Attendee SET phone_number = '+1234567890' WHERE attendee_id = 55;
DELETE FROM Attendee WHERE attendee_id = 182;
SELECT * FROM Attendee WHERE last_name LIKE 'M%';
UPDATE Attendee SET phone_number = '+1234567890' WHERE attendee_id = 78;
DELETE FROM Attendee WHERE attendee_id = 190;
SELECT * FROM Attendee WHERE last_name LIKE 'R%';
UPDATE Attendee SET phone_number = '+1234567890' WHERE attendee_id = 61;
DELETE FROM Attendee WHERE attendee_id = 135;
SELECT * FROM Attendee WHERE last_name LIKE 'B%';
UPDATE Attendee SET phone_number = '+1234567890' WHERE attendee_id = 41;
DELETE FROM Attendee WHERE attendee_id = 180;
SELECT * FROM Attendee WHERE last_name LIKE 'Z%';
UPDATE Attendee SET phone_number = '+1234567890' WHERE attendee_id = 99;
DELETE FROM Attendee WHERE attendee_id = 102;
SELECT * FROM Attendee WHERE last_name LIKE 'T%';
UPDATE Attendee SET phone_number = '+1234567890' WHERE attendee_id = 35;
DELETE FROM Attendee WHERE attendee_id = 169;
SELECT * FROM Attendee WHERE last_name LIKE 'F%';
UPDATE Attendee SET phone_number = '+1234567890' WHERE attendee_id = 47;
DELETE FROM Attendee WHERE attendee_id = 185;
SELECT * FROM Attendee WHERE last_name LIKE 'R%';
UPDATE Attendee SET phone_number = '+1234567890' WHERE attendee_id = 30;
DELETE FROM Attendee WHERE attendee_id = 120;
SELECT * FROM Attendee WHERE last_name LIKE 'P%';
UPDATE Attendee SET phone_number = '+1234567890' WHERE attendee_id = 84;
DELETE FROM Attendee WHERE attendee_id = 194;
SELECT * FROM Attendee WHERE last_name LIKE 'E%';
UPDATE Attendee SET phone_number = '+1234567890' WHERE attendee_id = 43;
DELETE FROM Attendee WHERE attendee_id = 150;
SELECT * FROM Attendee WHERE last_name LIKE 'O%';
UPDATE Attendee SET phone_number = '+1234567890' WHERE attendee_id = 27;
DELETE FROM Attendee WHERE attendee_id = 115;
SELECT * FROM Attendee WHERE last_name LIKE 'N%';
UPDATE Attendee SET phone_number = '+1234567890' WHERE attendee_id = 22;
DELETE FROM Attendee WHERE attendee_id = 159;
SELECT * FROM Attendee WHERE last_name LIKE 'D%';
UPDATE Attendee SET phone_number = '+1234567890' WHERE attendee_id = 60;
DELETE FROM Attendee WHERE attendee_id = 133;
SELECT * FROM Attendee WHERE last_name LIKE 'X%';
UPDATE Attendee SET phone_number = '+1234567890' WHERE attendee_id = 3;
DELETE FROM Attendee WHERE attendee_id = 108;
SELECT * FROM Attendee WHERE last_name LIKE 'A%';
UPDATE Attendee SET phone_number = '+1234567890' WHERE attendee_id = 50;
DELETE FROM Attendee WHERE attendee_id = 180;
SELECT * FROM Attendee WHERE last_name LIKE 'Y%';
UPDATE Attendee SET phone_number = '+1234567890' WHERE attendee_id = 13;
DELETE FROM Attendee WHERE attendee_id = 168;
SELECT * FROM Attendee WHERE last_name LIKE 'X%';
UPDATE Attendee SET phone_number = '+1234567890' WHERE attendee_id = 56;
DELETE FROM Attendee WHERE attendee_id = 123;
SELECT * FROM Attendee WHERE last_name LIKE 'Y%';
UPDATE Attendee SET phone_number = '+1234567890' WHERE attendee_id = 28;
DELETE FROM Attendee WHERE attendee_id = 151;
SELECT * FROM Attendee WHERE last_name LIKE 'I%';
UPDATE Attendee SET phone_number = '+1234567890' WHERE attendee_id = 76;
DELETE FROM Attendee WHERE attendee_id = 197;
SELECT * FROM Attendee WHERE last_name LIKE 'A%';
UPDATE Attendee SET phone_number = '+1234567890' WHERE attendee_id = 89;
DELETE FROM Attendee WHERE attendee_id = 176;

-- Staff --
SELECT first_name, last_name FROM Staff WHERE role_id = 7;
UPDATE Staff SET caption = 'Updated role' WHERE staff_id = 14;
SELECT first_name, last_name FROM Staff WHERE role_id = 1;
UPDATE Staff SET caption = 'Updated role' WHERE staff_id = 43;
SELECT first_name, last_name FROM Staff WHERE role_id = 6;
UPDATE Staff SET caption = 'Updated role' WHERE staff_id = 66;
SELECT first_name, last_name FROM Staff WHERE role_id = 2;
UPDATE Staff SET caption = 'Updated role' WHERE staff_id = 54;
SELECT first_name, last_name FROM Staff WHERE role_id = 4;
UPDATE Staff SET caption = 'Updated role' WHERE staff_id = 63;
SELECT first_name, last_name FROM Staff WHERE role_id = 5;
UPDATE Staff SET caption = 'Updated role' WHERE staff_id = 18;
SELECT first_name, last_name FROM Staff WHERE role_id = 8;
UPDATE Staff SET caption = 'Updated role' WHERE staff_id = 8;
SELECT first_name, last_name FROM Staff WHERE role_id = 6;
UPDATE Staff SET caption = 'Updated role' WHERE staff_id = 80;
SELECT first_name, last_name FROM Staff WHERE role_id = 5;
UPDATE Staff SET caption = 'Updated role' WHERE staff_id = 2;
SELECT first_name, last_name FROM Staff WHERE role_id = 3;
UPDATE Staff SET caption = 'Updated role' WHERE staff_id = 55;
SELECT first_name, last_name FROM Staff WHERE role_id = 7;
UPDATE Staff SET caption = 'Updated role' WHERE staff_id = 77;
SELECT first_name, last_name FROM Staff WHERE role_id = 3;
UPDATE Staff SET caption = 'Updated role' WHERE staff_id = 18;
SELECT first_name, last_name FROM Staff WHERE role_id = 1;
UPDATE Staff SET caption = 'Updated role' WHERE staff_id = 21;
SELECT first_name, last_name FROM Staff WHERE role_id = 8;
UPDATE Staff SET caption = 'Updated role' WHERE staff_id = 73;
SELECT first_name, last_name FROM Staff WHERE role_id = 4;
UPDATE Staff SET caption = 'Updated role' WHERE staff_id = 58;
SELECT first_name, last_name FROM Staff WHERE role_id = 5;
UPDATE Staff SET caption = 'Updated role' WHERE staff_id = 24;
SELECT first_name, last_name FROM Staff WHERE role_id = 1;
UPDATE Staff SET caption = 'Updated role' WHERE staff_id = 60;
SELECT first_name, last_name FROM Staff WHERE role_id = 6;
UPDATE Staff SET caption = 'Updated role' WHERE staff_id = 50;
SELECT first_name, last_name FROM Staff WHERE role_id = 7;
UPDATE Staff SET caption = 'Updated role' WHERE staff_id = 56;
SELECT first_name, last_name FROM Staff WHERE role_id = 1;
UPDATE Staff SET caption = 'Updated role' WHERE staff_id = 46;

-- Events --
SELECT title, start_dt, end_dt FROM Event WHERE is_full = FALSE;
UPDATE Event SET is_full = TRUE WHERE event_id = 39;
SELECT title, start_dt, end_dt FROM Event WHERE is_full = FALSE;
UPDATE Event SET is_full = TRUE WHERE event_id = 16;
SELECT title, start_dt, end_dt FROM Event WHERE is_full = FALSE;
UPDATE Event SET is_full = TRUE WHERE event_id = 31;
SELECT title, start_dt, end_dt FROM Event WHERE is_full = FALSE;
UPDATE Event SET is_full = TRUE WHERE event_id = 29;
SELECT title, start_dt, end_dt FROM Event WHERE is_full = FALSE;
UPDATE Event SET is_full = TRUE WHERE event_id = 22;
SELECT title, start_dt, end_dt FROM Event WHERE is_full = FALSE;
UPDATE Event SET is_full = TRUE WHERE event_id = 42;
SELECT title, start_dt, end_dt FROM Event WHERE is_full = FALSE;
UPDATE Event SET is_full = TRUE WHERE event_id = 12;
SELECT title, start_dt, end_dt FROM Event WHERE is_full = FALSE;
UPDATE Event SET is_full = TRUE WHERE event_id = 50;
SELECT title, start_dt, end_dt FROM Event WHERE is_full = FALSE;
UPDATE Event SET is_full = TRUE WHERE event_id = 28;
SELECT title, start_dt, end_dt FROM Event WHERE is_full = FALSE;
UPDATE Event SET is_full = TRUE WHERE event_id = 29;
SELECT title, start_dt, end_dt FROM Event WHERE is_full = FALSE;
UPDATE Event SET is_full = TRUE WHERE event_id = 15;
SELECT title, start_dt, end_dt FROM Event WHERE is_full = FALSE;
UPDATE Event SET is_full = TRUE WHERE event_id = 6;
SELECT title, start_dt, end_dt FROM Event WHERE is_full = FALSE;
UPDATE Event SET is_full = TRUE WHERE event_id = 9;
SELECT title, start_dt, end_dt FROM Event WHERE is_full = FALSE;
UPDATE Event SET is_full = TRUE WHERE event_id = 47;
SELECT title, start_dt, end_dt FROM Event WHERE is_full = FALSE;
UPDATE Event SET is_full = TRUE WHERE event_id = 30;
SELECT title, start_dt, end_dt FROM Event WHERE is_full = FALSE;
UPDATE Event SET is_full = TRUE WHERE event_id = 41;
SELECT title, start_dt, end_dt FROM Event WHERE is_full = FALSE;
UPDATE Event SET is_full = TRUE WHERE event_id = 42;
SELECT title, start_dt, end_dt FROM Event WHERE is_full = FALSE;
UPDATE Event SET is_full = TRUE WHERE event_id = 8;
SELECT title, start_dt, end_dt FROM Event WHERE is_full = FALSE;
UPDATE Event SET is_full = TRUE WHERE event_id = 11;
SELECT title, start_dt, end_dt FROM Event WHERE is_full = FALSE;
UPDATE Event SET is_full = TRUE WHERE event_id = 15;

-- Tickets --
SELECT * FROM Ticket WHERE cost > 209 ORDER BY cost DESC;
UPDATE Ticket SET status_id = 2 WHERE ticket_id = 42;
DELETE FROM Ticket WHERE ticket_id = 216;
SELECT * FROM Ticket WHERE cost > 254 ORDER BY cost DESC;
UPDATE Ticket SET status_id = 2 WHERE ticket_id = 55;
DELETE FROM Ticket WHERE ticket_id = 281;
SELECT * FROM Ticket WHERE cost > 100 ORDER BY cost DESC;
UPDATE Ticket SET status_id = 2 WHERE ticket_id = 99;
DELETE FROM Ticket WHERE ticket_id = 269;
SELECT * FROM Ticket WHERE cost > 187 ORDER BY cost DESC;
UPDATE Ticket SET status_id = 2 WHERE ticket_id = 15;
DELETE FROM Ticket WHERE ticket_id = 211;
SELECT * FROM Ticket WHERE cost > 256 ORDER BY cost DESC;
UPDATE Ticket SET status_id = 2 WHERE ticket_id = 46;
DELETE FROM Ticket WHERE ticket_id = 218;
SELECT * FROM Ticket WHERE cost > 156 ORDER BY cost DESC;
UPDATE Ticket SET status_id = 2 WHERE ticket_id = 34;
DELETE FROM Ticket WHERE ticket_id = 238;
SELECT * FROM Ticket WHERE cost > 293 ORDER BY cost DESC;
UPDATE Ticket SET status_id = 2 WHERE ticket_id = 79;
DELETE FROM Ticket WHERE ticket_id = 219;
SELECT * FROM Ticket WHERE cost > 77 ORDER BY cost DESC;
UPDATE Ticket SET status_id = 2 WHERE ticket_id = 78;
DELETE FROM Ticket WHERE ticket_id = 201;
SELECT * FROM Ticket WHERE cost > 57 ORDER BY cost DESC;
UPDATE Ticket SET status_id = 2 WHERE ticket_id = 60;
DELETE FROM Ticket WHERE ticket_id = 211;
SELECT * FROM Ticket WHERE cost > 232 ORDER BY cost DESC;
UPDATE Ticket SET status_id = 2 WHERE ticket_id = 32;
DELETE FROM Ticket WHERE ticket_id = 274;
SELECT * FROM Ticket WHERE cost > 242 ORDER BY cost DESC;
UPDATE Ticket SET status_id = 2 WHERE ticket_id = 47;
DELETE FROM Ticket WHERE ticket_id = 214;
SELECT * FROM Ticket WHERE cost > 109 ORDER BY cost DESC;
UPDATE Ticket SET status_id = 2 WHERE ticket_id = 47;
DELETE FROM Ticket WHERE ticket_id = 256;
SELECT * FROM Ticket WHERE cost > 298 ORDER BY cost DESC;
UPDATE Ticket SET status_id = 2 WHERE ticket_id = 93;
DELETE FROM Ticket WHERE ticket_id = 207;
SELECT * FROM Ticket WHERE cost > 109 ORDER BY cost DESC;
UPDATE Ticket SET status_id = 2 WHERE ticket_id = 43;
DELETE FROM Ticket WHERE ticket_id = 270;
SELECT * FROM Ticket WHERE cost > 248 ORDER BY cost DESC;
UPDATE Ticket SET status_id = 2 WHERE ticket_id = 88;
DELETE FROM Ticket WHERE ticket_id = 275;
SELECT * FROM Ticket WHERE cost > 212 ORDER BY cost DESC;
UPDATE Ticket SET status_id = 2 WHERE ticket_id = 19;
DELETE FROM Ticket WHERE ticket_id = 211;
SELECT * FROM Ticket WHERE cost > 151 ORDER BY cost DESC;
UPDATE Ticket SET status_id = 2 WHERE ticket_id = 83;
DELETE FROM Ticket WHERE ticket_id = 277;
SELECT * FROM Ticket WHERE cost > 143 ORDER BY cost DESC;
UPDATE Ticket SET status_id = 2 WHERE ticket_id = 49;
DELETE FROM Ticket WHERE ticket_id = 297;
SELECT * FROM Ticket WHERE cost > 187 ORDER BY cost DESC;
UPDATE Ticket SET status_id = 2 WHERE ticket_id = 77;
DELETE FROM Ticket WHERE ticket_id = 225;
SELECT * FROM Ticket WHERE cost > 73 ORDER BY cost DESC;
UPDATE Ticket SET status_id = 2 WHERE ticket_id = 63;
DELETE FROM Ticket WHERE ticket_id = 247;

-- Performances --
SELECT * FROM Performance WHERE duration BETWEEN 30 AND 120;
SELECT a.first_name, a.last_name FROM Artist a JOIN Performance_Artist pa ON a.artist_id = pa.artist_id WHERE perf_id = 32;
SELECT b.name FROM Band b JOIN Performance_Band pb ON b.band_id = pb.band_id WHERE perf_id = 24;
SELECT * FROM Performance WHERE duration BETWEEN 30 AND 120;
SELECT a.first_name, a.last_name FROM Artist a JOIN Performance_Artist pa ON a.artist_id = pa.artist_id WHERE perf_id = 3;
SELECT b.name FROM Band b JOIN Performance_Band pb ON b.band_id = pb.band_id WHERE perf_id = 34;
SELECT * FROM Performance WHERE duration BETWEEN 30 AND 120;
SELECT a.first_name, a.last_name FROM Artist a JOIN Performance_Artist pa ON a.artist_id = pa.artist_id WHERE perf_id = 34;
SELECT b.name FROM Band b JOIN Performance_Band pb ON b.band_id = pb.band_id WHERE perf_id = 17;
SELECT * FROM Performance WHERE duration BETWEEN 30 AND 120;
SELECT a.first_name, a.last_name FROM Artist a JOIN Performance_Artist pa ON a.artist_id = pa.artist_id WHERE perf_id = 18;
SELECT b.name FROM Band b JOIN Performance_Band pb ON b.band_id = pb.band_id WHERE perf_id = 23;
SELECT * FROM Performance WHERE duration BETWEEN 30 AND 120;
SELECT a.first_name, a.last_name FROM Artist a JOIN Performance_Artist pa ON a.artist_id = pa.artist_id WHERE perf_id = 48;
SELECT b.name FROM Band b JOIN Performance_Band pb ON b.band_id = pb.band_id WHERE perf_id = 41;
SELECT * FROM Performance WHERE duration BETWEEN 30 AND 120;
SELECT a.first_name, a.last_name FROM Artist a JOIN Performance_Artist pa ON a.artist_id = pa.artist_id WHERE perf_id = 23;
SELECT b.name FROM Band b JOIN Performance_Band pb ON b.band_id = pb.band_id WHERE perf_id = 14;
SELECT * FROM Performance WHERE duration BETWEEN 30 AND 120;
SELECT a.first_name, a.last_name FROM Artist a JOIN Performance_Artist pa ON a.artist_id = pa.artist_id WHERE perf_id = 15;
SELECT b.name FROM Band b JOIN Performance_Band pb ON b.band_id = pb.band_id WHERE perf_id = 39;
SELECT * FROM Performance WHERE duration BETWEEN 30 AND 120;
SELECT a.first_name, a.last_name FROM Artist a JOIN Performance_Artist pa ON a.artist_id = pa.artist_id WHERE perf_id = 7;
SELECT b.name FROM Band b JOIN Performance_Band pb ON b.band_id = pb.band_id WHERE perf_id = 11;
SELECT * FROM Performance WHERE duration BETWEEN 30 AND 120;
SELECT a.first_name, a.last_name FROM Artist a JOIN Performance_Artist pa ON a.artist_id = pa.artist_id WHERE perf_id = 35;
SELECT b.name FROM Band b JOIN Performance_Band pb ON b.band_id = pb.band_id WHERE perf_id = 31;
SELECT * FROM Performance WHERE duration BETWEEN 30 AND 120;
SELECT a.first_name, a.last_name FROM Artist a JOIN Performance_Artist pa ON a.artist_id = pa.artist_id WHERE perf_id = 18;
SELECT b.name FROM Band b JOIN Performance_Band pb ON b.band_id = pb.band_id WHERE perf_id = 22;
SELECT * FROM Performance WHERE duration BETWEEN 30 AND 120;
SELECT a.first_name, a.last_name FROM Artist a JOIN Performance_Artist pa ON a.artist_id = pa.artist_id WHERE perf_id = 44;
SELECT b.name FROM Band b JOIN Performance_Band pb ON b.band_id = pb.band_id WHERE perf_id = 27;
SELECT * FROM Performance WHERE duration BETWEEN 30 AND 120;
SELECT a.first_name, a.last_name FROM Artist a JOIN Performance_Artist pa ON a.artist_id = pa.artist_id WHERE perf_id = 12;
SELECT b.name FROM Band b JOIN Performance_Band pb ON b.band_id = pb.band_id WHERE perf_id = 12;
SELECT * FROM Performance WHERE duration BETWEEN 30 AND 120;
SELECT a.first_name, a.last_name FROM Artist a JOIN Performance_Artist pa ON a.artist_id = pa.artist_id WHERE perf_id = 45;
SELECT b.name FROM Band b JOIN Performance_Band pb ON b.band_id = pb.band_id WHERE perf_id = 14;
SELECT * FROM Performance WHERE duration BETWEEN 30 AND 120;
SELECT a.first_name, a.last_name FROM Artist a JOIN Performance_Artist pa ON a.artist_id = pa.artist_id WHERE perf_id = 35;
SELECT b.name FROM Band b JOIN Performance_Band pb ON b.band_id = pb.band_id WHERE perf_id = 39;
SELECT * FROM Performance WHERE duration BETWEEN 30 AND 120;
SELECT a.first_name, a.last_name FROM Artist a JOIN Performance_Artist pa ON a.artist_id = pa.artist_id WHERE perf_id = 12;
SELECT b.name FROM Band b JOIN Performance_Band pb ON b.band_id = pb.band_id WHERE perf_id = 27;
SELECT * FROM Performance WHERE duration BETWEEN 30 AND 120;
SELECT a.first_name, a.last_name FROM Artist a JOIN Performance_Artist pa ON a.artist_id = pa.artist_id WHERE perf_id = 21;
SELECT b.name FROM Band b JOIN Performance_Band pb ON b.band_id = pb.band_id WHERE perf_id = 22;
SELECT * FROM Performance WHERE duration BETWEEN 30 AND 120;
SELECT a.first_name, a.last_name FROM Artist a JOIN Performance_Artist pa ON a.artist_id = pa.artist_id WHERE perf_id = 10;
SELECT b.name FROM Band b JOIN Performance_Band pb ON b.band_id = pb.band_id WHERE perf_id = 25;
SELECT * FROM Performance WHERE duration BETWEEN 30 AND 120;
SELECT a.first_name, a.last_name FROM Artist a JOIN Performance_Artist pa ON a.artist_id = pa.artist_id WHERE perf_id = 33;
SELECT b.name FROM Band b JOIN Performance_Band pb ON b.band_id = pb.band_id WHERE perf_id = 19;
SELECT * FROM Performance WHERE duration BETWEEN 30 AND 120;
SELECT a.first_name, a.last_name FROM Artist a JOIN Performance_Artist pa ON a.artist_id = pa.artist_id WHERE perf_id = 17;
SELECT b.name FROM Band b JOIN Performance_Band pb ON b.band_id = pb.band_id WHERE perf_id = 10;
SELECT * FROM Performance WHERE duration BETWEEN 30 AND 120;
SELECT a.first_name, a.last_name FROM Artist a JOIN Performance_Artist pa ON a.artist_id = pa.artist_id WHERE perf_id = 16;
SELECT b.name FROM Band b JOIN Performance_Band pb ON b.band_id = pb.band_id WHERE perf_id = 15;

-- Joins and Reports --
SELECT f.name, e.title FROM Festival f JOIN Event e ON f.fest_year = e.fest_year WHERE e.is_full = FALSE;
SELECT t.ticket_id, a.first_name, a.last_name FROM Ticket t JOIN Attendee a ON t.attendee_id = a.attendee_id WHERE t.cost > 53;
SELECT f.name, e.title FROM Festival f JOIN Event e ON f.fest_year = e.fest_year WHERE e.is_full = FALSE;
SELECT t.ticket_id, a.first_name, a.last_name FROM Ticket t JOIN Attendee a ON t.attendee_id = a.attendee_id WHERE t.cost > 171;
SELECT f.name, e.title FROM Festival f JOIN Event e ON f.fest_year = e.fest_year WHERE e.is_full = FALSE;
SELECT t.ticket_id, a.first_name, a.last_name FROM Ticket t JOIN Attendee a ON t.attendee_id = a.attendee_id WHERE t.cost > 78;
SELECT f.name, e.title FROM Festival f JOIN Event e ON f.fest_year = e.fest_year WHERE e.is_full = FALSE;
SELECT t.ticket_id, a.first_name, a.last_name FROM Ticket t JOIN Attendee a ON t.attendee_id = a.attendee_id WHERE t.cost > 195;
SELECT f.name, e.title FROM Festival f JOIN Event e ON f.fest_year = e.fest_year WHERE e.is_full = FALSE;
SELECT t.ticket_id, a.first_name, a.last_name FROM Ticket t JOIN Attendee a ON t.attendee_id = a.attendee_id WHERE t.cost > 174;
SELECT f.name, e.title FROM Festival f JOIN Event e ON f.fest_year = e.fest_year WHERE e.is_full = FALSE;
SELECT t.ticket_id, a.first_name, a.last_name FROM Ticket t JOIN Attendee a ON t.attendee_id = a.attendee_id WHERE t.cost > 117;
SELECT f.name, e.title FROM Festival f JOIN Event e ON f.fest_year = e.fest_year WHERE e.is_full = FALSE;
SELECT t.ticket_id, a.first_name, a.last_name FROM Ticket t JOIN Attendee a ON t.attendee_id = a.attendee_id WHERE t.cost > 53;
SELECT f.name, e.title FROM Festival f JOIN Event e ON f.fest_year = e.fest_year WHERE e.is_full = FALSE;
SELECT t.ticket_id, a.first_name, a.last_name FROM Ticket t JOIN Attendee a ON t.attendee_id = a.attendee_id WHERE t.cost > 169;
SELECT f.name, e.title FROM Festival f JOIN Event e ON f.fest_year = e.fest_year WHERE e.is_full = FALSE;
SELECT t.ticket_id, a.first_name, a.last_name FROM Ticket t JOIN Attendee a ON t.attendee_id = a.attendee_id WHERE t.cost > 167;
SELECT f.name, e.title FROM Festival f JOIN Event e ON f.fest_year = e.fest_year WHERE e.is_full = FALSE;
SELECT t.ticket_id, a.first_name, a.last_name FROM Ticket t JOIN Attendee a ON t.attendee_id = a.attendee_id WHERE t.cost > 119;
SELECT f.name, e.title FROM Festival f JOIN Event e ON f.fest_year = e.fest_year WHERE e.is_full = FALSE;
SELECT t.ticket_id, a.first_name, a.last_name FROM Ticket t JOIN Attendee a ON t.attendee_id = a.attendee_id WHERE t.cost > 64;
SELECT f.name, e.title FROM Festival f JOIN Event e ON f.fest_year = e.fest_year WHERE e.is_full = FALSE;
SELECT t.ticket_id, a.first_name, a.last_name FROM Ticket t JOIN Attendee a ON t.attendee_id = a.attendee_id WHERE t.cost > 80;
SELECT f.name, e.title FROM Festival f JOIN Event e ON f.fest_year = e.fest_year WHERE e.is_full = FALSE;
SELECT t.ticket_id, a.first_name, a.last_name FROM Ticket t JOIN Attendee a ON t.attendee_id = a.attendee_id WHERE t.cost > 175;
SELECT f.name, e.title FROM Festival f JOIN Event e ON f.fest_year = e.fest_year WHERE e.is_full = FALSE;
SELECT t.ticket_id, a.first_name, a.last_name FROM Ticket t JOIN Attendee a ON t.attendee_id = a.attendee_id WHERE t.cost > 93;
SELECT f.name, e.title FROM Festival f JOIN Event e ON f.fest_year = e.fest_year WHERE e.is_full = FALSE;
SELECT t.ticket_id, a.first_name, a.last_name FROM Ticket t JOIN Attendee a ON t.attendee_id = a.attendee_id WHERE t.cost > 91;
SELECT f.name, e.title FROM Festival f JOIN Event e ON f.fest_year = e.fest_year WHERE e.is_full = FALSE;
SELECT t.ticket_id, a.first_name, a.last_name FROM Ticket t JOIN Attendee a ON t.attendee_id = a.attendee_id WHERE t.cost > 156;
SELECT f.name, e.title FROM Festival f JOIN Event e ON f.fest_year = e.fest_year WHERE e.is_full = FALSE;
SELECT t.ticket_id, a.first_name, a.last_name FROM Ticket t JOIN Attendee a ON t.attendee_id = a.attendee_id WHERE t.cost > 110;
SELECT f.name, e.title FROM Festival f JOIN Event e ON f.fest_year = e.fest_year WHERE e.is_full = FALSE;
SELECT t.ticket_id, a.first_name, a.last_name FROM Ticket t JOIN Attendee a ON t.attendee_id = a.attendee_id WHERE t.cost > 170;
SELECT f.name, e.title FROM Festival f JOIN Event e ON f.fest_year = e.fest_year WHERE e.is_full = FALSE;
SELECT t.ticket_id, a.first_name, a.last_name FROM Ticket t JOIN Attendee a ON t.attendee_id = a.attendee_id WHERE t.cost > 53;
SELECT f.name, e.title FROM Festival f JOIN Event e ON f.fest_year = e.fest_year WHERE e.is_full = FALSE;
SELECT t.ticket_id, a.first_name, a.last_name FROM Ticket t JOIN Attendee a ON t.attendee_id = a.attendee_id WHERE t.cost > 182;

-- Constraint Violations (Trigger Tests) --
-- SETUP: ensure foreign keys exist
INSERT INTO Stage (stage_id, name, capacity, image, caption) VALUES (1, 'Test Stage', 100, 'https://img.com/s.jpg', 'stage');
INSERT INTO Festival (fest_year, name, start_date, end_date, image, caption, loc_id) VALUES (2025, 'TestFest', '2025-06-01', '2025-06-10', 'https://img.com/f.jpg', 'fest', 1);
INSERT INTO Event (event_id, title, start_dt, end_dt, image, caption, fest_year, stage_id) VALUES (1, 'TestEvent', '2025-06-10 18:00:00', '2025-06-10 22:00:00', 'https://img.com/e.jpg', 'event', 2025, 1);
INSERT INTO Performance (perf_id, type_id, datetime, duration, break_duration, stage_id, event_id, sequence_number) VALUES (1, 1, '2025-06-10 19:00:00', 60, 10, 1, 1, 1);
INSERT INTO Artist (artist_id, first_name, last_name, date_of_birth, image, caption) VALUES (1, 'Test', 'Artist1', '1990-01-01', 'https://img.com/a1.jpg', 'caption');
INSERT INTO Artist (artist_id, first_name, last_name, date_of_birth, image, caption) VALUES (2, 'Test', 'Artist2', '1991-01-01', 'https://img.com/a2.jpg', 'caption');
-- TRIGGER TEST: Solo performance with too many artists
INSERT INTO Performance_Artist (perf_id, artist_id) VALUES (1, 1);
INSERT INTO Performance_Artist (perf_id, artist_id) VALUES (1, 2);  -- Should fail
